<h2 style="color:green" align="center">Machine Learning With Python: Save And Load Trained Model</h2>

In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [3]:
df = pd.read_csv('homeprices.csv')
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [4]:
model = linear_model.LinearRegression().fit(df[['area']],df.price)

In [5]:
model.coef_, model.intercept_

(array([135.78767123]), 180616.43835616432)

In [6]:
model.predict([[5000]])

C:\Users\karba\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

<h3 style="color:purple">Save model to a file using python pickle</h3>

In [7]:
import pickle

In [8]:
with open('model_pickle', 'wb') as f:
    pickle.dump(model,f)

<h3 style="color:purple">Load saved model</h3>

In [9]:
with open('model_pickle', 'rb') as f:
    mp = pickle.load(f)

In [10]:
mp.coef_, mp.intercept_

(array([135.78767123]), 180616.43835616432)

In [11]:
mp.predict([[5000]])

C:\Users\karba\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

<h3 style="color:purple">Save model to a file using joblib</h3>

In [15]:
import joblib

In [16]:
joblib.dump(model, 'model_joblib')

['model_joblib']

<h3 style="color:purple">Load saved model</h3>

In [17]:
mj = joblib.load('model_joblib')

In [18]:
mj.coef_, mj.intercept_

(array([135.78767123]), 180616.43835616432)

In [19]:
mj.predict([[5000]])

C:\Users\karba\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])